# Generated by Django 3.0.2 on 2020-03-07 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expensess', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensess',
            name='category_ID',
        ),
    ]
