# Generated by Django 3.0.2 on 2020-03-07 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensess', '0002_remove_expensess_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensess',
            name='memo',
            field=models.TextField(default=100),
            preserve_default=False,
        ),
    ]
