# Generated by Django 3.0.2 on 2020-04-17 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expensess', '0002_auto_20200327_1120'),
        ('expensess', '0004_auto_20200310_1154'),
    ]

    operations = [
    ]
